package emit

import (
	"strings"
	"testing"

	"github.com/mochilang/mochi-jvm/maven"
	javareflect "github.com/mochilang/mochi-jvm/reflect"
)

func fixtureCoord() maven.Coordinate {
	return maven.Coordinate{GroupID: "com.example", ArtifactID: "mylib", Version: "1.0.0"}
}

func fixtureSurface() *javareflect.Surface {
	return &javareflect.Surface{
		SchemaVersion: 1,
		Classes: []javareflect.ClassInfo{
			{
				Name:      "com.example.Greeter",
				Modifiers: []string{"public"},
				Methods: []javareflect.MethodInfo{
					{
						Name:           "greet",
						Modifiers:      []string{"public"},
						ReturnType:     "java.lang.String",
						ParameterTypes: []string{"java.lang.String"},
						ParameterNames: []string{"name"},
						ExceptionTypes: []string{},
					},
					{
						Name:           "getCount",
						Modifiers:      []string{"public", "static"},
						ReturnType:     "int",
						ParameterTypes: []string{},
						ExceptionTypes: []string{},
					},
				},
				Fields:       []javareflect.FieldInfo{},
				Constructors: []javareflect.ConstructorInfo{},
			},
		},
	}
}

func TestEmitShimMochi(t *testing.T) {
	shim := EmitShimMochi(fixtureSurface(), fixtureCoord())

	wantBits := []string{
		"Auto-generated by MEP-67",
		"com.example:mylib:1.0.0",
		"extern java type Greeter",
		"extern java fn",
		"handle: Greeter",
		"name: string",
	}
	for _, bit := range wantBits {
		if !strings.Contains(shim, bit) {
			t.Errorf("shim missing %q\n--- output ---\n%s", bit, shim)
		}
	}
}

func TestEmitShimMochiStaticMethod(t *testing.T) {
	shim := EmitShimMochi(fixtureSurface(), fixtureCoord())
	// Static method should not have handle parameter.
	if strings.Contains(shim, "static_getCount(handle:") {
		t.Errorf("static method should not have handle param:\n%s", shim)
	}
}
