// Package emit renders the Mochi extern shim file and the SKIPPED.txt report
// for the MEP-67 Java bridge.
package emit

import (
	"fmt"
	"strings"

	javaerrors "github.com/mochilang/mochi-jvm/errors"
	"github.com/mochilang/mochi-jvm/maven"
	javareflect "github.com/mochilang/mochi-jvm/reflect"
	"github.com/mochilang/mochi-jvm/typemap"
	"github.com/mochilang/mochi-jvm/wrapper"
)

// EmitShimMochi generates the .mochi extern shim file for a Java package.
// It synthesises wrapper calls for all translatable methods in the surface.
func EmitShimMochi(surface *javareflect.Surface, coord maven.Coordinate) string {
	var b strings.Builder
	b.WriteString("// Auto-generated by MEP-67 java bridge. Do not edit.\n")
	fmt.Fprintf(&b, "// Source: %s\n\n", coord.String())

	for _, cls := range surface.Classes {
		result := wrapper.Synth(cls)
		if len(result.WrapClass.Methods) == 0 && len(result.WrapClass.Fields) == 0 {
			continue
		}
		// Emit the opaque type declaration.
		typeName := classShortName(cls.Name)
		fmt.Fprintf(&b, "extern java type %s = %q\n", typeName, cls.Name)

		// Emit extern fn declarations for each method.
		for _, m := range result.WrapClass.Methods {
			line := externFnLine(m, typeName, cls.Name)
			if line != "" {
				b.WriteString(line)
				b.WriteString("\n")
			}
		}
		b.WriteString("\n")
	}
	return b.String()
}

// externFnLine renders a single `extern java fn` declaration.
func externFnLine(m wrapper.WrapMethod, typeName, origClass string) string {
	var params []string
	if !m.IsStatic {
		params = append(params, "handle: "+typeName)
	}
	for i, pm := range m.ParamMappings {
		name := paramName(m.ParamNames, i)
		params = append(params, name+": "+pm.MochiType)
	}
	retType := m.ReturnMapping.MochiType
	return fmt.Sprintf("extern java fn %s(%s): %s from %q",
		m.WrapName,
		strings.Join(params, ", "),
		retType,
		origClass+"."+m.OrigName)
}

// classShortName returns the unqualified class name.
func classShortName(name string) string {
	if idx := strings.LastIndex(name, "."); idx >= 0 {
		return name[idx+1:]
	}
	return name
}

// paramName returns the i-th parameter name.
func paramName(names []string, i int) string {
	if i < len(names) && names[i] != "" {
		return names[i]
	}
	return fmt.Sprintf("p%d", i)
}

// SkipReport is an aggregated skip entry from the emit phase.
type SkipReport = javaerrors.SkipReport

// EmitSkipReport renders a human-readable SKIPPED.txt for the given reports.
func EmitSkipReport(skips []javaerrors.SkipReport) string {
	if len(skips) == 0 {
		return "# No skipped items.\n"
	}
	var b strings.Builder
	b.WriteString("# Items skipped by the MEP-67 Java bridge.\n")
	fmt.Fprintf(&b, "# Total: %d\n\n", len(skips))
	for _, s := range skips {
		b.WriteString(s.String())
	}
	return b.String()
}

// CollectSkips collects SkipReports from a SynthResult.
func CollectSkips(cls javareflect.ClassInfo, result *wrapper.SynthResult) []javaerrors.SkipReport {
	var reports []javaerrors.SkipReport
	for _, se := range result.Skips {
		reports = append(reports, javaerrors.SkipReport{
			ItemPath: cls.Name + "." + se.Name,
			Reason:   parseSkipReason(se.Reason),
			Detail:   se.Reason,
		})
	}
	return reports
}

// parseSkipReason maps a skip reason string to the SkipReason enum.
func parseSkipReason(reason string) javaerrors.SkipReason {
	switch {
	case strings.Contains(reason, "SkipVarargs"):
		return javaerrors.SkipVarargs
	case strings.Contains(reason, "SkipNative"):
		return javaerrors.SkipNative
	case strings.Contains(reason, "SkipGeneric"):
		return javaerrors.SkipGeneric
	case strings.Contains(reason, "SkipWildcard"):
		return javaerrors.SkipWildcard
	case strings.Contains(reason, "SkipInnerClass"):
		return javaerrors.SkipInnerClass
	case strings.Contains(reason, "SkipReflective"):
		return javaerrors.SkipReflective
	case strings.Contains(reason, "SkipRawObject"):
		return javaerrors.SkipRawObject
	default:
		return javaerrors.SkipUnknown
	}
}

// Ensure typemap package is used.
var _ = typemap.KindString
