package wrapper

import (
	"strings"
	"testing"
)

func TestEmitJavaSource(t *testing.T) {
	result := Synth(fixtureClassInfo())
	src := EmitJavaSource(result.WrapClass)

	wantBits := []string{
		"Auto-generated by MEP-67",
		"public class MochiWrap_com_example_Greeter",
		"MochiWrap_com_example_Greeter_greet",
		"MochiWrap_com_example_Greeter_static_count",
		"long __handle",
		"String name",
	}
	for _, bit := range wantBits {
		if !strings.Contains(src, bit) {
			t.Errorf("EmitJavaSource missing %q\n--- output ---\n%s", bit, src)
		}
	}
}
