package wrapper

import (
	"fmt"
	"strings"

	"github.com/mochilang/mochi-jvm/typemap"
)

// EmitJavaSource renders the wrapper Java class source for a WrapClass.
// The emitted class has all methods as static so they can be called from JNI
// without an instance of the wrapper class.
func EmitJavaSource(wc *WrapClass) string {
	var b strings.Builder
	b.WriteString("// Auto-generated by MEP-67 Java bridge. Do not edit.\n")
	fmt.Fprintf(&b, "// Wraps: %s\n\n", wc.OrigClass)
	fmt.Fprintf(&b, "public class %s {\n", wc.ClassName)
	b.WriteString("\n")

	for _, m := range wc.Methods {
		writeWrapMethod(&b, wc.OrigClass, m)
	}

	b.WriteString("}\n")
	return b.String()
}

// writeWrapMethod emits a single wrapper method.
func writeWrapMethod(b *strings.Builder, origClass string, m WrapMethod) {
	retType := jniType(m.ReturnMapping)

	// Build parameter list. Instance methods get a "long handle" first.
	params := make([]string, 0)
	if !m.IsStatic {
		params = append(params, "long __handle")
	}
	for i, pm := range m.ParamMappings {
		name := paramName(m.ParamNames, i)
		params = append(params, jniType(pm)+" "+name)
	}

	fmt.Fprintf(b, "  public static %s %s(%s) {\n",
		retType, m.WrapName, strings.Join(params, ", "))

	// Emit the call.
	writeCallBody(b, origClass, m, retType)
	b.WriteString("  }\n\n")
}

// writeCallBody emits the body of the wrapper method.
func writeCallBody(b *strings.Builder, origClass string, m WrapMethod, retType string) {
	args := make([]string, 0, len(m.ParamMappings))
	for i, pm := range m.ParamMappings {
		name := paramName(m.ParamNames, i)
		args = append(args, castArg(pm, name))
	}
	argStr := strings.Join(args, ", ")

	if m.IsStatic {
		if m.ReturnMapping.Kind == typemap.KindVoid {
			fmt.Fprintf(b, "    %s.%s(%s);\n", origClass, m.OrigName, argStr)
		} else {
			fmt.Fprintf(b, "    return %s.%s(%s);\n", origClass, m.OrigName, argStr)
		}
	} else {
		fmt.Fprintf(b, "    %s __obj = (%s) MochiRuntime.deref(__handle);\n", origClass, origClass)
		if m.ReturnMapping.Kind == typemap.KindVoid {
			fmt.Fprintf(b, "    __obj.%s(%s);\n", m.OrigName, argStr)
		} else {
			fmt.Fprintf(b, "    return __obj.%s(%s);\n", m.OrigName, argStr)
		}
	}
}

// jniType returns the JNI-level Java type for a Mapping.
func jniType(m *typemap.Mapping) string {
	switch m.Kind {
	case typemap.KindInt:
		return "int"
	case typemap.KindLong:
		return "long"
	case typemap.KindBool:
		return "boolean"
	case typemap.KindFloat:
		return "float"
	case typemap.KindDouble:
		return "double"
	case typemap.KindVoid:
		return "void"
	case typemap.KindString:
		return "String"
	case typemap.KindBytes:
		return "byte[]"
	case typemap.KindHandle:
		return "long"
	case typemap.KindList, typemap.KindMap, typemap.KindOptional, typemap.KindFuture:
		// Serialised as JSON string across the JNI boundary.
		return "String"
	default:
		return "Object"
	}
}

// castArg returns the argument expression for a parameter, applying any needed cast.
func castArg(m *typemap.Mapping, name string) string {
	switch m.Kind {
	case typemap.KindHandle:
		// Handle is passed as long, cast to Object at call site.
		return fmt.Sprintf("(%s) MochiRuntime.deref(%s)", m.JavaName, name)
	default:
		return name
	}
}

// paramName returns the i-th parameter name, generating one if not available.
func paramName(names []string, i int) string {
	if i < len(names) && names[i] != "" {
		return names[i]
	}
	return fmt.Sprintf("p%d", i)
}
